env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
    - avoidEscape: true
  semi:
    - error
    - always
  "@typescript-eslint/no-unused-vars":
    - error
    - varsIgnorePattern: "[iI]gnored"
      argsIgnorePattern: "[iI]gnored"
      caughtErrorsIgnorePattern: "[iI]gnored"
