semi: true
singleQuote: false
printWidth: 80
tabWidth: 2
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: all
bracketSpacing: true
arrowParens: always
proseWrap: always
htmlWhitespaceSensitivity: css
overrides:
  - files:
      - "*.json"
      - "*.yaml"
      - "*.yml"
    options:
      tabWidth: 2
plugins:
  [
    "prettier-plugin-sort-json",
    "prettier-plugin-package",
    "prettier-plugin-jsdoc",
  ]
